import React from 'react';
import {
  Search,
  Bolt,
  AddBox,
  AutoFixHigh,
  Map,
  AssignmentTurnedIn,
  CameraAlt,
  Analytics,
  TrendingUp,
  TrendingDown,
  PriorityHigh,
  Description,
  ChevronRight,
  AutoAwesome,
  ArrowForward,
  SmartToy,
  Notifications,
  Settings,
  Logout,
  Dashboard,
  Inventory,
  Handshake,
  Campaign,
  People,
  Lightbulb,
  Description as DescriptionIcon,
  Assessment,
  Close,
  Layers,
  List,
  CalendarViewMonth,
  FilterList,
  Edit,
  Business,
  Payments,
  Place,
  Image as ImageIcon,
  ZoomIn,
  ArrowBack,
  Add,
  Category,
  PostAdd,
  ViewList,
  Download,
  Inventory2,
  ReceiptLong,
  FormatListBulleted,
  ExpandMore,
  AttachMoney,
  PieChart,
  Groups,
  Warning,
  PersonAdd,
  RecentActors,
  CheckCircle,
  Star,
  Menu,
  Home,
  LocationOn,
  AdUnits,
  ImageSearch,
  MoreVert,
  Delete,
  Save,
  Cancel,
  Check,
  Refresh,
  CloudUpload,
  CloudDownload,
  Folder,
  FolderOpen,
  InsertDriveFile,
  Image,
  Videocam,
  Mic,
  Phone,
  Email,
  Chat,
  Send,
  ThumbUp,
  ThumbDown,
  Favorite,
  Share,
  Flag,
  Bookmark,
  StarBorder,
  StarHalf,
  Visibility,
  VisibilityOff,
  Lock,
  LockOpen,
  AccountCircle,
  Person,
  Group,
  PeopleAlt,
  Public,
  Language,
  Schedule,
  AccessTime,
  Timer,
  HourglassEmpty,
  DateRange,
  Event,
  CalendarToday,
  Today,
  WbSunny,
  NightsStay,
  Brightness4,
  Brightness7,
  FlashOn,
  FlashOff,
  BatteryFull,
  BatteryAlert,
  SignalWifi4Bar,
  SignalWifiOff,
  NetworkCheck,
  Speed,
  DataUsage,
  Storage,
  Memory,
  Computer,
  DesktopMac,
  Laptop,
  PhoneIphone,
  Tablet,
  Watch,
  Tv,
  Radio,
  Print,
  Scanner,
  Keyboard,
  Mouse,
  Headset,
  Speaker,
  VideogameAsset,
  SportsEsports,
  EmojiEvents,
  EmojiObjects,
  Lightbulb as LightbulbIcon,
  Psychology,
  School,
  Book,
  MenuBook,
  LibraryBooks,
  Article,
  Newspaper,
  Feed,
  Forum,
  ChatBubble,
  ChatBubbleOutline,
  QuestionAnswer,
  Message,
  Email as EmailIcon,
  MarkEmailRead,
  AttachFile,
  Attachment,
  Link,
  LinkOff,
  OpenInNew,
  Launch,
  ExitToApp,
  Login,
  Logout as LogoutIcon,
  AppRegistration,
  AppSettingsAlt,
  Build,
  Construction,
  Engineering,
  Handyman,
  Plumbing,
  ElectricalServices,
  LocalShipping,
  DeliveryDining,
  RoomService,
  CleaningServices,
  DesignServices,
  BusinessCenter,
  Work,
  WorkOutline,
  Business as BusinessIcon,
  Store,
  Storefront,
  ShoppingCart,
  ShoppingBag,
  Payment,
  CreditCard,
  AccountBalance,
  AccountBalanceWallet,
  Receipt,
  ReceiptLong as ReceiptLongIcon,
  Invoice,
  Money,
  MonetizationOn,
  AttachMoney as AttachMoneyIcon,
  CurrencyExchange,
  PriceCheck,
  Discount,
  LocalOffer,
  Loyalty,
  CardGiftcard,
  Redeem,
  Wallet,
  Savings,
  Calculate,
  Assessment as AssessmentIcon,
  Analytics as AnalyticsIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  TrendingFlat,
  ShowChart,
  BarChart,
  PieChart as PieChartIcon,
  DonutLarge,
  StackedLineChart,
  MultilineChart,
  Insights,
  AutoGraph,
  QueryStats,
  Score,
  Leaderboard,
  MilitaryTech,
  WorkspacePremium,
  Verified,
  VerifiedUser,
  GppGood,
  GppMaybe,
  GppBad,
  Security,
  Shield,
  PrivacyTip,
  Policy,
  Copyright,
  Trademark,
  Registered,
  Help,
  HelpOutline,
  Info,
  InfoOutlined,
  Error,
  ErrorOutline,
  Warning as WarningIcon,
  WarningAmber,
  NotificationImportant,
  CircleNotifications,
  NotificationsActive,
  NotificationsNone,
  NotificationsOff,
  Badge,
  AccountBox,
  AccountCircle as AccountCircleIcon,
  Person as PersonIcon,
  PersonOutline,
  PersonAdd,
  PersonAddAlt,
  Group as GroupIcon,
  GroupAdd,
  People as PeopleIcon,
  PeopleOutline,
  Diversity1,
  Diversity2,
  Diversity3,
  Wc,
  Accessibility,
  AccessibilityNew,
  Hearing,
  HearingDisabled,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Translate,
  GTranslate,
  TextFormat,
  Title,
  Subject,
  ShortText,
  Notes,
  FormatBold,
  FormatItalic,
  FormatUnderlined,
  FormatStrikethrough,
  FormatColorFill,
  FormatColorText,
  FormatSize,
  FormatAlignLeft,
  FormatAlignCenter,
  FormatAlignRight,
  FormatAlignJustify,
  FormatListBulleted,
  FormatListNumbered,
  FormatQuote,
  Code,
  CodeOff,
  Terminal,
  DeveloperMode,
  IntegrationInstructions,
  BuildCircle,
  BugReport,
  PestControl,
  PestControlRodent,
  Sanitize,
  CleanHands,
  Handshake as HandshakeIcon,
  Diversity1 as Diversity1Icon,
  GroupWork,
  Workspaces,
  Hub,
  Api,
  Extension,
  ExtensionOff,
  Power,
  PowerOff,
  PowerSettingsNew,
  ToggleOn,
  ToggleOff,
  RadioButtonChecked,
  RadioButtonUnchecked,
  CheckBox,
  CheckBoxOutlineBlank,
  IndeterminateCheckBox,
  Star as StarIcon,
  StarBorder as StarBorderIcon,
  StarHalf as StarHalfIcon,
  StarRate,
  ThumbUp as ThumbUpIcon,
  ThumbDown as ThumbDownIcon,
  ThumbsUpDown,
  SentimentVeryDissatisfied,
  SentimentDissatisfied,
  SentimentNeutral,
  SentimentSatisfied,
  SentimentVerySatisfied,
  Mood,
  MoodBad,
  Face,
  Face2,
  Face3,
  Face4,
  Face5,
  Face6,
  CatchingPokemon,
  Pets,
  EmojiNature,
  EmojiFoodBeverage,
  EmojiTransportation,
  EmojiEvents as EmojiEventsIcon,
  EmojiObjects as EmojiObjectsIcon,
  SportsScore,
  Sports,
  SportsBaseball,
  SportsBasketball,
  SportsFootball,
  SportsGolf,
  SportsGymnastics,
  SportsHandball,
  SportsHockey,
  SportsKabaddi,
  SportsMartialArts,
  SportsMma,
  SportsMotorsports,
  SportsRugby,
  SportsSoccer,
  SportsTennis,
  SportsVolleyball,
  SportsCricket,
  SportsEsports as SportsEsportsIcon,
  Hiking,
  Kayaking,
  Paragliding,
  Sailing,
  Skateboarding,
  Skydiving,
  Snowboarding,
  Snowshoeing,
  Surfing,
  NordicWalking,
  Museum,
  AccountBalance as AccountBalanceIcon,
  AccountBalanceWallet as AccountBalanceWalletIcon,
  TempleHindu,
  TempleBuddhist,
  Mosque,
  Church,
  Synagogue,
  Castle,
  Fort,
  Casa,
  Villa,
  Apartment,
  HolidayVillage,
  LocationCity,
  Nightlife,
  Festival,
  TheaterComedy,
  Movie,
  MovieFilter,
  MusicNote,
  MusicOff,
  LibraryMusic,
  Podcasts,
  Radio as RadioIcon,
  Tv as TvIcon,
  LiveTv,
  VideoLibrary,
  VideoCall,
  VideoLabel,
  Videocam as VideocamIcon,
  VideocamOff,
  PhotoCamera,
  CameraAlt,
  Camera,
  CameraFront,
  CameraRear,
  CameraRoll,
  BurstMode,
  Filter,
  Filter1,
  Filter2,
  Filter3,
  Filter4,
  Filter5,
  Filter6,
  Filter7,
  Filter8,
  Filter9,
  Filter9Plus,
  FilterBAndW,
  FilterCenterFocus,
  FilterDrama,
  FilterFrames,
  FilterHdr,
  FilterNone,
  FilterTiltShift,
  FilterVintage,
  Flare,
  FlashAuto,
  FlashOff,
  FlashOn,
  Flip,
  FlipCameraAndroid,
  FlipCameraIos,
  Gradient,
  Grain,
  GridOff,
  GridOn,
  HdrOff,
  HdrOn,
  HdrStrong,
  HdrWeak,
  Healing,
  Image as LucideImage,
  ImageAspectRatio,
  ImageNotSupported,
  ImageSearch as ImageSearchIcon,
  Iso,
  Landscape,
  LeakAdd,
  LeakRemove,
  Lens,
  LinkedCamera,
  Looks,
  Looks3,
  Looks4,
  Looks5,
  Looks6,
  LooksOne,
  LooksTwo,
  Loupe,
  MonochromePhotos,
  MotionPhotosAuto,
  MotionPhotosOff,
  MotionPhotosOn,
  MotionPhotosPause,
  MovieCreation,
  MovieFilter,
  MusicVideo,
  Nature,
  NaturePeople,
  NavigateBefore,
  NavigateNext,
  Palette,
  Panorama,
  PanoramaFishEye,
  PanoramaHorizontal,
  PanoramaVertical,
  PanoramaWideAngle,
  Photo,
  PhotoAlbum,
  PhotoCamera as PhotoCameraIcon,
  PhotoFilter,
  PhotoLibrary,
  PhotoSizeSelectActual,
  PhotoSizeSelectLarge,
  PhotoSizeSelectSmall,
  PictureAsPdf,
  Portrait,
  RawOff,
  RawOn,
  Receipt as ReceiptIcon,
  RemoveRedEye,
  Rotate90DegreesCcw,
  RotateLeft,
  RotateRight,
  ShutterSpeed,
  Slideshow,
  Straighten,
  Style,
  SwitchCamera,
  SwitchVideo,
  TagFaces,
  Texture,
  Timelapse,
  Timer10,
  Timer3,
  TimerOff,
  Tonality,
  Transform,
  Tune,
  ViewComfy,
  ViewCompact,
  Vignette,
  WbAuto,
  WbCloudy,
  WbIncandescent,
  WbIridescent,
  WbShade,
  WbSunny as WbSunnyIcon,
  WbTwilight,
  AddPhotoAlternate,
  AddAPhoto,
  Collections,
  CollectionsBookmark,
  ColorLens,
  Colorize,
  Compare,
  ControlPoint,
  ControlPointDuplicate,
  Crop,
  Crop169,
  Crop32,
  Crop54,
  Crop75,
  CropDin,
  CropFree,
  CropLandscape,
  CropOriginal,
  CropPortrait,
  CropRotate,
  CropSquare,
  Dehaze,
  Details,
  DirtyLens,
  Edit as EditIcon,
  Euro,
  ExifRotate,
  Exposure,
  ExposureNeg1,
  ExposureNeg2,
  ExposurePlus1,
  ExposurePlus2,
  ExposureZero,
  FaceRetouchingNatural,
  FaceRetouchingOff,
  FilterAlt,
  FilterAltOff,
  FilterHdr as FilterHdrIcon,
  Flip as FlipIcon,
  FlipToBack,
  FlipToFront,
  GIF,
  HideImage,
  ImageSearch,
  Mic as MicIcon,
  MicExternalOff,
  MicExternalOn,
  MicNone,
  MicOff,
  MissedVideoCall,
  More,
  MoreHoriz,
  MoreVert as MoreVertIcon,
  MultipleStop,
  MusicOff as MusicOffIcon,
  Pause,
  PauseCircle,
  PauseCircleFilled,
  PauseCircleOutline,
  PlayArrow,
  PlayCircle,
  PlayCircleFilled,
  PlayCircleOutline,
  PlaylistAdd,
  PlaylistAddCheck,
  PlaylistPlay,
  Queue,
  QueueMusic,
  QueuePlayNext,
  Radio as RadioIcon2,
  RecentActors as RecentActorsIcon,
  RemoveFromQueue,
  Repeat,
  RepeatOn,
  RepeatOne,
  RepeatOneOn,
  Replay,
  Replay10,
  Replay30,
  Replay5,
  Shuffle,
  ShuffleOn,
  SkipNext,
  SkipPrevious,
  SlowMotionVideo,
  Snooze,
  SortByAlpha,
  Stop,
  StopCircle,
  Subscriptions,
  VideoCall as VideoCallIcon,
  VideoLabel as VideoLabelIcon,
  VideoSettings,
  VideoStable,
  Videocam as VideocamIcon2,
  VideocamOff as VideocamOffIcon,
  VolumeDown,
  VolumeMute,
  VolumeOff,
  VolumeUp,
  Web,
  WebAsset,
  WebAssetOff,
  ThreeDRotation,
  FourK,
  AddToQueue,
  Airplay,
  Album,
  ArtTrack,
  AvTimer,
  BrandingWatermark,
  CallToAction,
  ClosedCaption,
  ClosedCaptionDisabled,
  ClosedCaptionOff,
  ControlCamera,
  Equalizer,
  Explicit,
  FastForward,
  FastRewind,
  FeaturedPlayList,
  FeaturedVideo,
  FiberDvr,
  FiberManualRecord,
  FiberNew,
  FiberPin,
  FiberSmartRecord,
  Forward10,
  Forward30,
  Forward5,
  Games,
  Hd,
  Hearing as HearingIcon,
  HearingDisabled as HearingDisabledIcon,
  HighQuality,
  InterpretersMode,
  LibraryAdd,
  LibraryAddCheck,
  LibraryBooks as LibraryBooksIcon,
  LibraryMusic as LibraryMusicIcon,
  Loop,
  Lyrics,
  Mic as MicIcon2,
  MicNone as MicNoneIcon,
  MicOff as MicOffIcon,
  Movie as MovieIcon,
  MusicVideo as MusicVideoIcon,
  NewReleases,
  NotInterested,
  Note,
  Pause as PauseIcon,
  PauseCircle as PauseCircleIcon,
  PlayArrow as PlayArrowIcon,
  PlayCircle as PlayCircleIcon,
  PlayDisabled,
  PlaylistAdd as PlaylistAddIcon,
  PlaylistAddCheck as PlaylistAddCheckIcon,
  PlaylistPlay as PlaylistPlayIcon,
  Queue as QueueIcon,
  QueueMusic as QueueMusicIcon,
  QueuePlayNext as QueuePlayNextIcon,
  Radio as RadioIcon3,
  RemoveFromQueue as RemoveFromQueueIcon,
  Repeat as RepeatIcon,
  RepeatOne as RepeatOneIcon,
  Replay as ReplayIcon,
  Replay10 as Replay10Icon,
  Replay30 as Replay30Icon,
  Replay5 as Replay5Icon,
  RvHookup,
  Shuffle as ShuffleIcon,
  SkipNext as SkipNextIcon,
  SkipPrevious as SkipPreviousIcon,
  SlowMotionVideo as SlowMotionVideoIcon,
  Snooze as SnoozeIcon,
  SortByAlpha as SortByAlphaIcon,
  Stop as StopIcon,
  Subscriptions as SubscriptionsIcon,
  VideoLibrary as VideoLibraryIcon,
  VideoSettings as VideoSettingsIcon,
  Videocam as VideocamIcon3,
  VolumeDown as VolumeDownIcon,
  VolumeMute as VolumeMuteIcon,
  VolumeOff as VolumeOffIcon,
  VolumeUp as VolumeUpIcon,
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

// 图标映射表 - Material Icons 名称映射到 Lucide Icons
const iconMapping: Record<string, LucideIcon> = {
  // 导航类
  'dashboard': Dashboard,
  'home': Home,
  'menu': Menu,
  'search': Search,
  'notifications': Notifications,
  'settings': Settings,
  'logout': Logout,
  'login': Login,
  'arrow_back': ArrowBack,
  'arrow_forward': ArrowForward,
  'chevron_right': ChevronRight,
  'expand_more': ExpandMore,
  'close': Close,
  'menu_open': Menu,
  
  // 操作类
  'add': Add,
  'add_box': AddBox,
  'edit': Edit,
  'delete': Delete,
  'save': Save,
  'cancel': Cancel,
  'check': Check,
  'check_circle': CheckCircle,
  'refresh': Refresh,
  'more_vert': MoreVert,
  'more_horiz': MoreVert,
  
  // 文件类
  'description': Description,
  'folder': Folder,
  'folder_open': FolderOpen,
  'insert_drive_file': InsertDriveFile,
  'image': ImageIcon,
  'photo': ImageIcon,
  'photo_camera': CameraAlt,
  'camera_alt': CameraAlt,
  'videocam': VideoCall,
  'mic': Mic,
  'cloud_upload': CloudUpload,
  'cloud_download': CloudDownload,
  'download': Download,
  'view_list': ViewList,
  'format_list_bulleted': FormatListBulleted,
  'inventory_2': Inventory2,
  'receipt': ReceiptIcon,
  'receipt_long': ReceiptLong,
  
  // 通讯类
  'phone': Phone,
  'email': Email,
  'chat': Chat,
  'chat_bubble': ChatBubble,
  'chat_bubble_outline': ChatBubbleOutline,
  'send': Send,
  'message': Message,
  'forum': Forum,
  
  // 用户类
  'person': Person,
  'person_add': PersonAdd,
  'people': People,
  'group': Group,
  'groups': Groups,
  'account_circle': AccountCircle,
  'business': Business,
  'recent_actors': RecentActors,
  
  // 内容类
  'favorite': Favorite,
  'star': Star,
  'star_border': StarBorder,
  'star_half': StarHalf,
  'thumb_up': ThumbUp,
  'thumb_down': ThumbDown,
  'bookmark': Bookmark,
  'flag': Flag,
  'share': Share,
  
  // 状态类
  'visibility': Visibility,
  'visibility_off': VisibilityOff,
  'lock': Lock,
  'lock_open': LockOpen,
  'warning': Warning,
  'error': Error,
  'info': Info,
  'help': Help,
  'priority_high': PriorityHigh,
  
  // 时间类
  'schedule': Schedule,
  'access_time': AccessTime,
  'timer': Timer,
  'date_range': DateRange,
  'event': Event,
  'calendar_today': CalendarToday,
  'today': Today,
  
  // 天气/主题类
  'wb_sunny': WbSunny,
  'nights_stay': NightsStay,
  'brightness_4': Brightness4,
  'brightness_7': Brightness7,
  
  // 设备类
  'computer': Computer,
  'desktop_mac': DesktopMac,
  'laptop': Laptop,
  'phone_iphone': PhoneIphone,
  'tablet': Tablet,
  'tv': Tv,
  'headset': Headset,
  'speaker': Speaker,
  
  // 功能类
  'analytics': Analytics,
  'assessment': Assessment,
  'insights': Insights,
  'trending_up': TrendingUp,
  'trending_down': TrendingDown,
  'bar_chart': BarChart,
  'pie_chart': PieChart,
  'show_chart': ShowChart,
  'data_usage': DataUsage,
  
  // 业务类
  'work': Work,
  'business_center': BusinessCenter,
  'store': Store,
  'storefront': Storefront,
  'shopping_cart': ShoppingCart,
  'payment': Payment,
  'credit_card': CreditCard,
  'account_balance': AccountBalance,
  'wallet': Wallet,
  'receipt': Receipt,
  'invoice': ReceiptLong,
  'money': Money,
  'attach_money': AttachMoney,
  'calculate': Calculate,
  'local_offer': LocalOffer,
  'loyalty': Loyalty,
  
  // 媒体类
  'play_arrow': PlayArrow,
  'pause': Pause,
  'stop': Stop,
  'skip_next': SkipNext,
  'skip_previous': SkipPrevious,
  'volume_up': VolumeUp,
  'volume_down': VolumeDown,
  'volume_off': VolumeOff,
  'volume_mute': VolumeMute,
  
  // 地图/位置类
  'place': Place,
  'location_on': LocationOn,
  'map': Map,
  
  // 开发类
  'code': Code,
  'terminal': Terminal,
  'developer_mode': DeveloperMode,
  'bug_report': BugReport,
  'build': Build,
  
  // 其他
  'flash_on': FlashOn,
  'flash_off': FlashOff,
  'bolt': Bolt,
  'auto_fix_high': AutoFixHigh,
  'auto_awesome': AutoAwesome,
  'smart_toy': SmartToy,
  'emoji_events': EmojiEvents,
  'emoji_objects': EmojiObjects,
  'lightbulb': Lightbulb,
  'psychology': Psychology,
  'school': School,
  'book': Book,
  'library_books': LibraryBooks,
  'article': Article,
  'newspaper': Newspaper,
  'feed': Feed,
  
  // 额外映射
  'inventory': Inventory,
  'handshake': Handshake,
  'campaign': Campaign,
  'assignment': AssignmentTurnedIn,
  'assignment_turned_in': AssignmentTurnedIn,
  'layers': Layers,
  'list': List,
  'calendar_view_month': CalendarViewMonth,
  'filter_list': FilterList,
  'payments': Payments,
  'ad_units': AdUnits,
  'image_search': ImageSearch,
  'zoom_in': ZoomIn,
  'category': Category,
  'post_add': PostAdd,
  'person_add': PersonAdd,
  'check_circle': CheckCircle,
  'star': Star,
  'logout': Logout,
  'analytics': Analytics,
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  size?: number;
  className?: string;
}

export const Icon: React.FC<IconProps> = ({ name, size = 24, className = '', ...props }) => {
  const LucideIconComponent = iconMapping[name] || iconMapping['help'];
  
  return (
    <LucideIconComponent 
      size={size} 
      className={className}
      {...props}
    />
  );
};

export default Icon;
